<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tomar Screenshot</name>
   <tag></tag>
   <elementGuidId>850758d5-1a61-486b-93a8-8824005c4c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#screenshot-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='screenshot-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tomar Screenshot&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>085731e6-892a-46c4-bf63-06a1d75b51f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa20be55-af27-48d4-bd02-1d4287031a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>1e067772-0085-41d3-8d56-7cd5170d0240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>screenshot-btn</value>
      <webElementGuid>9bb56a1e-431d-416c-b191-97391faf9ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tomar Screenshot</value>
      <webElementGuid>d6427f50-e32a-4dc8-8e73-e4926cc43bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;screenshot-btn&quot;)</value>
      <webElementGuid>0ffd8d59-0da6-4de7-88cb-5d6aaa546f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='screenshot-btn']</value>
      <webElementGuid>6e677bb3-f891-47a3-98cc-32c308cfb575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminos y Condiciones'])[1]/following::button[1]</value>
      <webElementGuid>5034c37f-20de-405e-bb9f-04af3d1c2c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenidos a la lista de tareas'])[1]/following::button[1]</value>
      <webElementGuid>3136cd0b-3a94-4b55-9585-e829fe0d3c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tomar Screenshot']/parent::*</value>
      <webElementGuid>9610b791-8c2e-440e-acd6-e7b0db768eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8d744811-1527-404c-86af-f2da48d1edeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'screenshot-btn' and (text() = 'Tomar Screenshot' or . = 'Tomar Screenshot')]</value>
      <webElementGuid>2ddabcb1-22d8-465b-822b-7c1a6412380e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
