<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Descargar</name>
   <tag></tag>
   <elementGuidId>983f55ac-f21c-454a-89d4-2ed54df9985b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#download-pdf-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='download-pdf-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Descargar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f378bb94-66b5-410c-a26a-8fe92c8e5cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>download-pdf-btn</value>
      <webElementGuid>98e7049e-05d5-443e-a7ca-907a88a15e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descargar</value>
      <webElementGuid>ae56f36a-01ae-44a3-aee8-8b1312ab2f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-pdf-btn&quot;)</value>
      <webElementGuid>79c6d8a5-a63d-413d-956b-030706676726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='download-pdf-btn']</value>
      <webElementGuid>11b2ec7a-de57-410a-99ec-e192085778d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/following::button[1]</value>
      <webElementGuid>db4cbd63-da04-4ca1-8e0f-78a8368fcb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[2]</value>
      <webElementGuid>91108c4f-69b4-4d88-a03d-27e5c0f761d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descargar']/parent::*</value>
      <webElementGuid>1120882c-cfe9-4221-ab92-e751701d816d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>4470f48e-70de-4719-8f8d-2b0b9f205e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'download-pdf-btn' and (text() = 'Descargar' or . = 'Descargar')]</value>
      <webElementGuid>4b8f953d-8291-4309-ad0b-c2837be98ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
