<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tareas_task-input</name>
   <tag></tag>
   <elementGuidId>a2d0dcd6-bffa-4d94-9d6e-66a2565cfa35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='task-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tareas&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d12a77fc-c607-4c8d-a018-197f6cfff2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ed968f1-a8dc-4a3c-a4d0-e57237c4d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task-input</value>
      <webElementGuid>066043c2-2201-4ae6-a18b-0692a45fc28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-input&quot;)</value>
      <webElementGuid>a3fcab56-7815-4b96-9afb-1bfb0df083ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='task-input']</value>
      <webElementGuid>6ae4ba92-b1b3-40b3-861f-a032ed3517df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>695f53c4-a809-41b3-851f-9bedcda29c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'task-input']</value>
      <webElementGuid>cc8ed266-325f-4902-8b4f-0352e61fac54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
