<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tareas_task-input</name>
   <tag></tag>
   <elementGuidId>a2d0dcd6-bffa-4d94-9d6e-66a2565cfa35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='task-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tareas&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>903b054c-1498-4155-9b42-b15d9ddd9bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc88f9ed-13d7-4cd8-b9e8-a8607513a804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task-input</value>
      <webElementGuid>bcc344d0-4a54-47f7-a8c3-347f629a8f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-input&quot;)</value>
      <webElementGuid>86881fd9-23e0-4530-ba01-eac4fc0a3aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='task-input']</value>
      <webElementGuid>9d825c97-74b1-4af7-964c-4d6244537cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>b64ec750-d70b-42a9-98de-dcadeabad152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'task-input']</value>
      <webElementGuid>755501e4-63ae-4ba3-ab0d-febdde0f3357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
