<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tareas_task-input</name>
   <tag></tag>
   <elementGuidId>a2d0dcd6-bffa-4d94-9d6e-66a2565cfa35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='task-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tareas&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3efeee19-17ba-4c79-bb74-dc4d2a62f7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7c1b08c-82ed-4d1c-b7bb-e0a33df94e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task-input</value>
      <webElementGuid>b30f2ee0-cf63-4c09-81fc-17adfcc37273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-input&quot;)</value>
      <webElementGuid>3a19a6a2-4752-4aa4-ac35-34a2aa009c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='task-input']</value>
      <webElementGuid>cf0a46ea-f925-46d8-a26c-6b16e480e7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>985d5f6f-b141-4124-bfbd-43cd032f3677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'task-input']</value>
      <webElementGuid>dd646869-f181-4168-9eea-86f019c16a8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
