<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PersonalTrabajoComprasCitasEjercicio_dcdaaf</name>
   <tag></tag>
   <elementGuidId>84495901-54ea-4a78-9aad-52cc4bdfa3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='category-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoría&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6fa27349-f121-463c-a1bf-696751758de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category-select</value>
      <webElementGuid>c64ac650-537c-4c13-a586-361c362b238f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PersonalTrabajoComprasCitasEjercicioAcadémicasTécnicas</value>
      <webElementGuid>5d0547f2-a57f-4cd1-b6aa-7f79b1e9f277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category-select&quot;)</value>
      <webElementGuid>aaf6e51b-220b-4be9-a6b5-ada92880e8e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='category-select']</value>
      <webElementGuid>4be67854-b4d4-47ec-b1e1-21f1cbe3ee71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría'])[1]/following::select[1]</value>
      <webElementGuid>03fe1853-ad21-4308-9b74-3374ffd37219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tareas'])[1]/following::select[1]</value>
      <webElementGuid>fc4e1647-0d67-4df9-98a3-34ff02725176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>8d9ec45a-7fc2-4383-9667-eb2ef2eb3c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/preceding::select[1]</value>
      <webElementGuid>13ade14b-627a-43d2-8126-aa8958aacc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ce784a57-6752-4992-98bc-6297be04f405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'category-select' and (text() = 'PersonalTrabajoComprasCitasEjercicioAcadémicasTécnicas' or . = 'PersonalTrabajoComprasCitasEjercicioAcadémicasTécnicas')]</value>
      <webElementGuid>889e7568-843f-4d18-95d7-4bc8df71632a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
