<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PersonalTrabajoComprasCitasEjercicio_dcdaaf</name>
   <tag></tag>
   <elementGuidId>84495901-54ea-4a78-9aad-52cc4bdfa3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='category-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoría&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c5dfe96-cb96-4081-8c8b-2d9aa0ac6ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category-select</value>
      <webElementGuid>c6105131-e2d8-4fcb-9571-e9260b89137e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PersonalTrabajoComprasCitasEjercicioAcadémicasTécnicas</value>
      <webElementGuid>dd9814be-6a47-4a3e-977a-080cfe70fa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category-select&quot;)</value>
      <webElementGuid>06e0bba9-f231-491e-b41b-5feeea57a5a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='category-select']</value>
      <webElementGuid>e30eb1de-c7eb-4ead-8888-9192ec7ee8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría'])[1]/following::select[1]</value>
      <webElementGuid>4267d245-e8ef-440a-8d1e-38e6abfb19fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tareas'])[1]/following::select[1]</value>
      <webElementGuid>7b721e27-fbc1-4b0e-a4d9-c2f89f1e5336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>77f3c9ed-7e91-4dad-8dee-d689a5f4dc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/preceding::select[1]</value>
      <webElementGuid>3af7ac2c-88a5-43fc-9f58-d2aae9ca71ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>27e43079-5226-40b7-a691-3791cfd3a8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'category-select' and (text() = 'PersonalTrabajoComprasCitasEjercicioAcadémicasTécnicas' or . = 'PersonalTrabajoComprasCitasEjercicioAcadémicasTécnicas')]</value>
      <webElementGuid>8921eee2-f220-4bca-bab7-a20ab5d924b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
